# Generated by Django 3.2.6 on 2022-08-29 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clark_id', models.CharField(editable=False, max_length=6, null=True, unique=True)),
                ('budget', models.FloatField(default=0.0)),
                ('title', models.CharField(max_length=30, unique=True)),
                ('division', models.CharField(choices=[('Clark Base', 'Base'), ('Clark Civil', 'Civil'), ('Clark Foundation', 'Foundation'), ('Clark Water', 'Water'), ('Clark Concrete', 'Concrete'), ('C3M', 'C3M'), ('Atkinson', 'Atkinson'), ('Shirley', 'Shirley'), ('CODA', 'Coda'), ('CARTA', 'Carta')], max_length=50, null=True)),
                ('delivery_method', models.CharField(choices=[('Design-Bid-Build', 'Dbbuild'), ('Design-Build', 'Dbuild'), ('Construction Manager at Risk (CMAR)', 'Cmar')], max_length=50, null=True)),
                ('client', models.CharField(max_length=30, null=True)),
                ('venture', models.CharField(max_length=30, null=True)),
                ('structure', models.CharField(choices=[('PEMB', 'Pemb'), ('Steel', 'Steel'), ('Concrete', 'Concrete'), ('Composite', 'Composite'), ('Underground Utility', 'Uu'), ('Tunneling', 'Tunnel'), ('Sheeting/Shoring', 'Sheet'), ('Process Piping', 'Procp'), ('Bridge', 'Bridge'), ('Road', 'Road')], max_length=50, null=True)),
                ('due', models.DateField(null=True)),
                ('ntp', models.CharField(max_length=30, null=True)),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.locality')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.state')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='home.team')),
            ],
        ),
        migrations.CreateModel(
            name='LessonLearned',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('permission_level', models.CharField(blank=True, choices=[('Private', 'Private'), ('Project', 'Project'), ('Public', 'Public')], default='Private', max_length=50)),
                ('project_phase', models.CharField(choices=[('Initial (Precon)', 'Initial'), ('Planning/Execution', 'Plan'), ('Close out', 'Close Out')], default='Initial (Precon)', max_length=50)),
                ('category', models.CharField(blank=True, choices=[('Marketing/Pursuing (Bid/Legal)', 'Marketing'), ('Purchasing/Business Management', 'Business'), ('HR/Team Setup', 'Hr'), ('Mobilization/Permit', 'Permit'), ('Safety', 'Safety'), ('QC', 'Qc'), ('Scheduling', 'Scheduling'), ('Procurement/Supply Chain/Inflation', 'Sc'), ('Change Order Management', 'Change Order'), ('Stakeholder Management', 'Stakeholder Mgt'), ('Document Control Management', 'Doc Mgt'), ('Punch Out', 'Po')], max_length=50, null=True)),
                ('impact', models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Moderate', 'Moderate'), ('Negative', 'Negative')], max_length=50, null=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Pending Review', 'Pending Review'), ('Approved', 'Approved'), ('Change Requested', 'Change Requested'), ('Rejected', 'Rejected')], default='Draft', max_length=50)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='home.account')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='home.team'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
