# Generated by Django 3.2.6 on 2022-08-29 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_lessonlearned_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonlearned',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='home.account'),
        ),
    ]
