# Generated by Django 3.2.6 on 2022-08-29 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_lessonlearned_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='locality',
        ),
    ]
