# Generated by Django 3.2.6 on 2022-08-29 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_project_locality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='state',
        ),
    ]
