# Generated by Django 3.2.6 on 2022-08-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_project_clark_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='clark_id',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
